baseurl: "/"
languageCode: "en-us"
title: "webcodr"
metaDataFormat: "yaml"
theme: "webcodr"
permalinks:
  post: /:year/:month/:slug/
canonifyURLs: true
enableRobotsTXT: true
staticDir: ["static"]
pygmentsCodefences: true
pygmentsUseClasses: true
blackfriday:
  plainIDAnchors: false
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
pagination.pagerSize: 5
