baseurl: "https://webcodr.io/"
languageCode: "de-de"
title: "WebCodr"
metaDataFormat: "yaml"
theme: "webcodr"
permalinks:
  post: /:year/:month/:title/
canonifyURLs: true
enableRobotsTXT: true
staticDir: ["static"]
