baseurl: "/"
locale: "en-us"
title: "webcodr"
theme: "webcodr"
permalinks:
  post: /:year/:month/:slug/
canonifyURLs: true
enableRobotsTXT: true
staticDir: ["static"]
markup:
  highlight:
    codeFences: true
    noClasses: false
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
pagination.pagerSize: 5
