baseurl: "/"
locale: "en-us"
title: "webcodr"
theme: "webcodr"
permalinks:
  post: /:year/:month/:slug/
canonifyURLs: true
enableRobotsTXT: true
staticDir: ["static"]
markup:
  highlight:
    codeFences: true
    noClasses: false
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
services:
  rss:
    limit: 20
pagination:
  pagerSize: 5
taxonomies:
  topic: topics
related:
  includeNewer: true
  threshold: 80
  toLower: true
  indices:
    - name: topics
      weight: 100
    - name: date
      weight: 10
