services:
  caddy:
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./public:/srv
      - ./../../caddy_data:/data
      - ./../../caddy_config:/config
    networks:
      - caddy

networks:
  caddy:
    enable_ipv6: true


